<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
     <NoWarn>CS8618;CS8602;CS8604;CS1591;CS0168;CS0618;CS8601;CS8618;CS8602;CS8604;CS0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="swashbuckle.aspnetcore" Version="9.0.4" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppQR.Core\AppQR.Core.csproj" />
    <ProjectReference Include="..\AppQR.Dapper\AppQR.Dapper.csproj" />
    <ProjectReference Include="..\AppQR.Services\AppQR.Services.csproj" />
  </ItemGroup>

</Project>
